In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
l = ['a','b','c']
display(type(l))
display(l)


list

['a', 'b', 'c']

In [3]:
l = np.array(['a','b','c'])
display(type(l))
display(l)

numpy.ndarray

array(['a', 'b', 'c'], dtype='<U1')

# Series Data type in pandas

In [4]:
l = pd.Series(['a','b','c'])
display(type(l))
display(l)

pandas.core.series.Series

0    a
1    b
2    c
dtype: object

In [5]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]

display(type(l))
display(l)

list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
l = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])

display(type(l))
display(l)

numpy.ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
l = pd.DataFrame([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

display(type(l))
display(l)

pandas.core.frame.DataFrame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# How we can create Series in pandas?
* list
* tuple
* dictionary
* 1-D array
* list for index and list for values


In [8]:
l = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
display(type(l))
display(l)


l = pd.Series(l)
display(type(l))
display(l)


list

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

pandas.core.series.Series

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
dtype: object

In [9]:
l = tuple('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
display(type(l))
display(l)


l = pd.Series(l)
display(type(l))
display(l)


tuple

('A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z')

pandas.core.series.Series

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
dtype: object

In [12]:
l = set('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
display(type(l))
display(l)


l = pd.Series(l)
display(type(l))
display(l)


set

{'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z'}

TypeError: 'set' type is unordered

In [13]:
l = {
    "A":"Pakistan",
    "B":"China",
    "C":"America"
}

display(type(l))
display(l)


l = pd.Series(l)
display(type(l))
display(l)


dict

{'A': 'Pakistan', 'B': 'China', 'C': 'America'}

pandas.core.series.Series

A    Pakistan
B       China
C     America
dtype: object

In [14]:
i = ["A","B","C"]
v = [100,200,300]

l = pd.Series(v,i)
display(l)
l = pd.Series(data=v, index=i)
display(l)

A    100
B    200
C    300
dtype: int64

A    100
B    200
C    300
dtype: int64

In [15]:
n = np.random.randint(1,100, 10)
display(n)

pd.Series(n)

array([54, 43, 65,  3, 67,  7, 25, 79, 75, 58])

0    54
1    43
2    65
3     3
4    67
5     7
6    25
7    79
8    75
9    58
dtype: int32

In [16]:
l = [100,200,300]


l = pd.Series(l, name='abcd')
display(type(l))
display(l)


pandas.core.series.Series

0    100
1    200
2    300
Name: abcd, dtype: int64

In [17]:
l = [100,200,300]


l = pd.Series(l, name='abcd', dtype=np.int32)
display(type(l))
display(l)


pandas.core.series.Series

0    100
1    200
2    300
Name: abcd, dtype: int32

# How can we create dataframe in pandas?
* matrics
    * list of list
    * tupl of tuple
* dictionary
* 2-D array
* dataframe attributes
    * dtype
    * shape
    

In [18]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]

df = pd.DataFrame(l)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
l = ((1,2,3),
    (4,5,6),
    (7,8,9))

df = pd.DataFrame(l)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [20]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]

n = np.array(l)

df = pd.DataFrame(n)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]

n = np.array(l)

df = pd.DataFrame(n, columns=["id",'name','cnic'])
df

id  name  cnic
0   1     2     3
1   4     5     6
2   7     8     9

In [22]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]

n = np.array(l)

df = pd.DataFrame(n, 
                  columns=["id",'name','cnic'],
                 index=['a','b','c'])
df

id  name  cnic
a   1     2     3
b   4     5     6
c   7     8     9

# dataframe components
* column index
* row index
* values

In [23]:
display(df)

display(df.columns)
display(df.index)
display(df.values)

id  name  cnic
a   1     2     3
b   4     5     6
c   7     8     9

Index(['id', 'name', 'cnic'], dtype='object')

Index(['a', 'b', 'c'], dtype='object')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# dated: 6-Jun-2023

In [27]:
cols = [["AI","AI","Web","Web"],
       ["id",'name','id','name']]

data = np.random.randint(1,100,size=(5,4))

df = pd.DataFrame(data,columns=cols)
df

AI      Web     
   id name  id name
0  89   70  89   25
1  46   84   8   68
2  50   10  66    9
3  55   91  85   97
4  37   69  39   87

# multi rows index

In [31]:
rows_index = [["Sind",'Sind',"Punjab","Punjab"],
             ["Karachi",'Hyderabad','Lahore',"Faislabad"]]

data = [200,300,150,175]

df = pd.DataFrame(data, 
                  columns=["No of Students"],
                 index=rows_index)
df

No of Students
Sind   Karachi               200
       Hyderabad             300
Punjab Lahore                150
       Faislabad             175

In [33]:
rows_index = [["Sind",'Sind',"Punjab","Punjab"],
             ["Karachi",'Hyderabad','Lahore',"Faislabad"]]

data = [200,300,150,175]

df = pd.Series(data,
                 index=rows_index)
df

Sind    Karachi      200
        Hyderabad    300
Punjab  Lahore       150
        Faislabad    175
dtype: int64

# 01 Filtering data from dataframe
* columns and values
    * single value
    * multiples values
* boolean slicing
* slicing
    * loc
    * iloc

Note: must be verify data type of any column before apply any filter operation    

In [71]:
def name_generator(max_len):
    r = np.random.randint(3,max_len,1)[0]
    fc = chr(np.random.randint(65,90,1)[0])
    remaing_letters = np.random.randint(97,122,r)
    remaing_letters = list(map(chr, remaing_letters))
    return fc+"".join(remaing_letters)

print(name_generator(5))

list(map(name_generator,np.random.randint(4,20,3)))


Amee


['Upgphbkm', 'Jbov', 'Xndqtujsw']

In [116]:
def dob_generator(start, end):
    year = np.random.randint(start,end,1)[0]
    month = np.random.randint(1,12,1)[0]
    day = np.random.randint(1,28,1)[0]
    
    
    return pd.to_datetime(f'{year}/{month}/{day}')

dob_generator(1970,2017)

Timestamp('2011-02-06 00:00:00')

In [123]:
# [dob_generator(1969,i) for i in np.random.randint(1970,2017,100)]

In [132]:
samples = 10000

df = pd.DataFrame({
    "roll_no":np.arange(1, samples+1),
    "Name": list(map(name_generator,np.random.randint(4,20,samples))),
    "Father Name": list(map(name_generator,np.random.randint(4,20,samples))),
    "Course": np.random.choice(["AI","Web","Chatbot","Graphic","Video"], samples),
     "Fee": np.random.choice([1000,1500,2000], samples),
    "dob": [dob_generator(1969,i) for i in np.random.randint(1970,2017,samples)]
})

df1 = pd.DataFrame(np.random.randint(1,100,size=(samples,5)),
                  columns=["s1",'s2','s3','s4','s5'])
df1



df = pd.concat([df,df1], axis=1)

df

roll_no             Name    Father Name   Course   Fee        dob  s1  \
0           1          Hiylida          Bxolo  Chatbot  1000 1970-03-09  38   
1           2       Evkataxmok           Dmke  Graphic  1500 1972-06-11  93   
2           3       Srcpjlvdyw       Crjtbubj  Chatbot  2000 1983-04-27  70   
3           4             Qhxw          Ebwyn  Chatbot  1500 1997-10-13  98   
4           5             Yqru     Tkcqbfvlhf    Video  1000 1990-04-27  53   
...       ...              ...            ...      ...   ...        ...  ..   
9995     9996          Hmnhivq          Omico  Graphic  1500 1970-08-18   1   
9996     9997           Wibebo      Aaafyjxbr    Video  2000 1983-08-22  64   
9997     9998            Rdmdy          Fmtop  Graphic  1000 1970-04-03  79   
9998     9999         Thicutou          Vxxfp       AI  1500 1969-03-25  18   
9999    10000  Phorraovxvndvvn  Hgekbvecpalkk  Chatbot  1000 1970-09-04  62   

      s2  s3  s4  s5  
0     36  91  46  78  
1     29   1  81  35  
2     64   8  45  54  
3     33  22  48  95  
4     47  59  61  77  
...   ..  ..  ..  ..  
9995  96  46  19  18  
9996  85  16   8   9  
9997  77  93   1  25  
9998  41  34  24  12  
9999  73  66  12  71  

[10000 rows x 11 columns]

# EDA

* info()
* describe()

In [137]:
df.head()# 1-60

roll_no        Name Father Name   Course   Fee        dob  s1  s2  s3  s4  \
0        1     Hiylida       Bxolo  Chatbot  1000 1970-03-09  38  36  91  46   
1        2  Evkataxmok        Dmke  Graphic  1500 1972-06-11  93  29   1  81   
2        3  Srcpjlvdyw    Crjtbubj  Chatbot  2000 1983-04-27  70  64   8  45   
3        4        Qhxw       Ebwyn  Chatbot  1500 1997-10-13  98  33  22  48   
4        5        Yqru  Tkcqbfvlhf    Video  1000 1990-04-27  53  47  59  61   

   s5  
0  78  
1  35  
2  54  
3  95  
4  77

In [139]:
df.tail()# 1-60

roll_no             Name    Father Name   Course   Fee        dob  s1  \
9995     9996          Hmnhivq          Omico  Graphic  1500 1970-08-18   1   
9996     9997           Wibebo      Aaafyjxbr    Video  2000 1983-08-22  64   
9997     9998            Rdmdy          Fmtop  Graphic  1000 1970-04-03  79   
9998     9999         Thicutou          Vxxfp       AI  1500 1969-03-25  18   
9999    10000  Phorraovxvndvvn  Hgekbvecpalkk  Chatbot  1000 1970-09-04  62   

      s2  s3  s4  s5  
9995  96  46  19  18  
9996  85  16   8   9  
9997  77  93   1  25  
9998  41  34  24  12  
9999  73  66  12  71

In [141]:
df.sample(5)# random samples

roll_no        Name     Father Name   Course   Fee        dob  s1  s2  \
3989     3990      Nclnel           Hfuhv  Graphic  1000 1969-02-21  51  98   
7437     7438       Iljga  Fiputnelepvsfc      Web  1000 1985-11-24  42  53   
3977     3978        Mbnp         Nqueluq    Video  1000 2009-03-22  52  17   
2587     2588        Njnb            Dgem    Video  1000 1971-05-26  12  80   
826       827  Wytvvuuhmq            Rver       AI  2000 2006-10-08   4  80   

      s3  s4  s5  
3989  44  29  35  
7437  99  39  36  
3977   6  27  50  
2587  62  87  72  
826   42  48  67

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   roll_no      10000 non-null  int32         
 1   Name         10000 non-null  object        
 2   Father Name  10000 non-null  object        
 3   Course       10000 non-null  object        
 4   Fee          10000 non-null  int32         
 5   dob          10000 non-null  datetime64[ns]
 6   s1           10000 non-null  int32         
 7   s2           10000 non-null  int32         
 8   s3           10000 non-null  int32         
 9   s4           10000 non-null  int32         
 10  s5           10000 non-null  int32         
dtypes: datetime64[ns](1), int32(7), object(3)
memory usage: 586.1+ KB


In [143]:
df.describe()

roll_no           Fee            s1            s2           s3  \
count  10000.00000  10000.000000  10000.000000  10000.000000  10000.00000   
mean    5000.50000   1502.950000     50.664400     50.105600     49.90090   
std     2886.89568    410.710562     28.566988     28.663029     28.62428   
min        1.00000   1000.000000      1.000000      1.000000      1.00000   
25%     2500.75000   1000.000000     26.000000     25.000000     25.00000   
50%     5000.50000   1500.000000     51.000000     50.000000     50.00000   
75%     7500.25000   2000.000000     75.250000     75.000000     75.00000   
max    10000.00000   2000.000000     99.000000     99.000000     99.00000   

                 s4            s5  
count  10000.000000  10000.000000  
mean      49.803100     50.043500  
std       28.339531     28.873881  
min        1.000000      1.000000  
25%       25.000000     25.000000  
50%       50.000000     50.000000  
75%       74.000000     75.000000  
max       99.000000     99.000000

# Mean/Average

In [145]:
a = np.array([100,80,70,40,150,50,30])
a

array([100,  80,  70,  40, 150,  50,  30])

In [146]:
print(a.sum()/len(a))

74.28571428571429


In [147]:
a = np.array([100,80,70,40,150,50,800])
print(a.sum()/len(a))


184.28571428571428


# Median

In [150]:
# step sort
display(a)
b = sorted(a)
display(b)
# if count is odd number then middle number will be "Median"
print("80 is your median or center tendancy ")


array([100,  80,  70,  40, 150,  50, 800])

[40, 50, 70, 80, 100, 150, 800]

80 is your median or center tendancy 


In [151]:
a = np.array([100,80,70,40,150,50,200,800])

# step sort
display(a)
b = sorted(a)
display(b)
# if count is odd number then middle number will be "Median"
print(" 80, 100 = 80+100/2 = 90 is your median or center tendancy ")


array([100,  80,  70,  40, 150,  50, 200, 800])

[40, 50, 70, 80, 100, 150, 200, 800]

80 is your median or center tendancy 


In [152]:
a = np.array([100,80,70,40,150,50,70,800])

# step sort
display(a)
b = sorted(a)
display(b)
# if count is odd number then middle number will be "Median"
print(" 70 is mode number ")


array([100,  80,  70,  40, 150,  50,  70, 800])

[40, 50, 70, 70, 80, 100, 150, 800]

 70 is mode number 


In [158]:
display(a)
display(a.mean())# average
display(np.median(a))#


array([100,  80,  70,  40, 150,  50,  70, 800])

170.0

75.0

In [160]:
from scipy import stats

stats.mode(a)

C:\Users\saylani\AppData\Local\Temp\ipykernel_17548\1113305435.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)


ModeResult(mode=array([70]), count=array([2]))